# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import warehouse_pb2 as warehouse__pb2


class WarehouseControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/warehouse.WarehouseController/List',
                request_serializer=warehouse__pb2.WarehouseListRequest.SerializeToString,
                response_deserializer=warehouse__pb2.Warehouse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/warehouse.WarehouseController/Retrieve',
                request_serializer=warehouse__pb2.WarehouseRetrieveRequest.SerializeToString,
                response_deserializer=warehouse__pb2.Warehouse.FromString,
                )
        self.Create = channel.unary_unary(
                '/warehouse.WarehouseController/Create',
                request_serializer=warehouse__pb2.Warehouse.SerializeToString,
                response_deserializer=warehouse__pb2.Warehouse.FromString,
                )
        self.Change = channel.unary_unary(
                '/warehouse.WarehouseController/Change',
                request_serializer=warehouse__pb2.Warehouse.SerializeToString,
                response_deserializer=warehouse__pb2.Warehouse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/warehouse.WarehouseController/Delete',
                request_serializer=warehouse__pb2.WarehouseRetrieveRequest.SerializeToString,
                response_deserializer=warehouse__pb2.Warehouse.FromString,
                )
        self.Iso = channel.unary_stream(
                '/warehouse.WarehouseController/Iso',
                request_serializer=warehouse__pb2.WarehouseIsoRequest.SerializeToString,
                response_deserializer=warehouse__pb2.Isochrone.FromString,
                )
        self.NearestStation = channel.unary_unary(
                '/warehouse.WarehouseController/NearestStation',
                request_serializer=warehouse__pb2.WarehouseRetrieveRequest.SerializeToString,
                response_deserializer=warehouse__pb2.Warehouse.FromString,
                )


class WarehouseControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Change(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Iso(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NearestStation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WarehouseControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=warehouse__pb2.WarehouseListRequest.FromString,
                    response_serializer=warehouse__pb2.Warehouse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=warehouse__pb2.WarehouseRetrieveRequest.FromString,
                    response_serializer=warehouse__pb2.Warehouse.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=warehouse__pb2.Warehouse.FromString,
                    response_serializer=warehouse__pb2.Warehouse.SerializeToString,
            ),
            'Change': grpc.unary_unary_rpc_method_handler(
                    servicer.Change,
                    request_deserializer=warehouse__pb2.Warehouse.FromString,
                    response_serializer=warehouse__pb2.Warehouse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=warehouse__pb2.WarehouseRetrieveRequest.FromString,
                    response_serializer=warehouse__pb2.Warehouse.SerializeToString,
            ),
            'Iso': grpc.unary_stream_rpc_method_handler(
                    servicer.Iso,
                    request_deserializer=warehouse__pb2.WarehouseIsoRequest.FromString,
                    response_serializer=warehouse__pb2.Isochrone.SerializeToString,
            ),
            'NearestStation': grpc.unary_unary_rpc_method_handler(
                    servicer.NearestStation,
                    request_deserializer=warehouse__pb2.WarehouseRetrieveRequest.FromString,
                    response_serializer=warehouse__pb2.Warehouse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'warehouse.WarehouseController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WarehouseController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/warehouse.WarehouseController/List',
            warehouse__pb2.WarehouseListRequest.SerializeToString,
            warehouse__pb2.Warehouse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/warehouse.WarehouseController/Retrieve',
            warehouse__pb2.WarehouseRetrieveRequest.SerializeToString,
            warehouse__pb2.Warehouse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/warehouse.WarehouseController/Create',
            warehouse__pb2.Warehouse.SerializeToString,
            warehouse__pb2.Warehouse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Change(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/warehouse.WarehouseController/Change',
            warehouse__pb2.Warehouse.SerializeToString,
            warehouse__pb2.Warehouse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/warehouse.WarehouseController/Delete',
            warehouse__pb2.WarehouseRetrieveRequest.SerializeToString,
            warehouse__pb2.Warehouse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Iso(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/warehouse.WarehouseController/Iso',
            warehouse__pb2.WarehouseIsoRequest.SerializeToString,
            warehouse__pb2.Isochrone.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NearestStation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/warehouse.WarehouseController/NearestStation',
            warehouse__pb2.WarehouseRetrieveRequest.SerializeToString,
            warehouse__pb2.Warehouse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
