# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warehouse.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\x12\twarehouse\x1a\x1bgoogle/protobuf/empty.proto\"5\n\tWarehouse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05phone\x18\x02 \x01(\t\x12\r\n\x05point\x18\x03 \x01(\t\"\x16\n\x14WarehouseListRequest2X\n\x13WarehouseController\x12\x41\n\x04List\x12\x1f.warehouse.WarehouseListRequest\x1a\x14.warehouse.Warehouse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WAREHOUSE']._serialized_start=59
  _globals['_WAREHOUSE']._serialized_end=112
  _globals['_WAREHOUSELISTREQUEST']._serialized_start=114
  _globals['_WAREHOUSELISTREQUEST']._serialized_end=136
  _globals['_WAREHOUSECONTROLLER']._serialized_start=138
  _globals['_WAREHOUSECONTROLLER']._serialized_end=226
# @@protoc_insertion_point(module_scope)
