# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: warehouse.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fwarehouse.proto\x12\twarehouse\x1a\x1bgoogle/protobuf/empty.proto\"q\n\tWarehouse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05phone\x18\x02 \x01(\t\x12\r\n\x05point\x18\x03 \x01(\t\x12\x1a\n\x12nearest_railway_id\x18\x04 \x01(\x03\x12\x1e\n\x16nearest_railway_length\x18\x05 \x01(\x02\"\x16\n\x14WarehouseListRequest\"&\n\x18WarehouseRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"4\n\x13WarehouseIsoRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\ttimespans\x18\x02 \x01(\t\"Q\n\tIsochrone\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x0cwarehouse_id\x18\x02 \x01(\x03\x12\x10\n\x08timespan\x18\x03 \x01(\x03\x12\x10\n\x08\x61ll_geom\x18\x04 \x01(\t2\xe8\x03\n\x13WarehouseController\x12\x41\n\x04List\x12\x1f.warehouse.WarehouseListRequest\x1a\x14.warehouse.Warehouse\"\x00\x30\x01\x12G\n\x08Retrieve\x12#.warehouse.WarehouseRetrieveRequest\x1a\x14.warehouse.Warehouse\"\x00\x12\x36\n\x06\x43reate\x12\x14.warehouse.Warehouse\x1a\x14.warehouse.Warehouse\"\x00\x12\x36\n\x06\x43hange\x12\x14.warehouse.Warehouse\x1a\x14.warehouse.Warehouse\"\x00\x12\x45\n\x06\x44\x65lete\x12#.warehouse.WarehouseRetrieveRequest\x1a\x14.warehouse.Warehouse\"\x00\x12?\n\x03Iso\x12\x1e.warehouse.WarehouseIsoRequest\x1a\x14.warehouse.Isochrone\"\x00\x30\x01\x12M\n\x0eNearestStation\x12#.warehouse.WarehouseRetrieveRequest\x1a\x14.warehouse.Warehouse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'warehouse_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_WAREHOUSE']._serialized_start=59
  _globals['_WAREHOUSE']._serialized_end=172
  _globals['_WAREHOUSELISTREQUEST']._serialized_start=174
  _globals['_WAREHOUSELISTREQUEST']._serialized_end=196
  _globals['_WAREHOUSERETRIEVEREQUEST']._serialized_start=198
  _globals['_WAREHOUSERETRIEVEREQUEST']._serialized_end=236
  _globals['_WAREHOUSEISOREQUEST']._serialized_start=238
  _globals['_WAREHOUSEISOREQUEST']._serialized_end=290
  _globals['_ISOCHRONE']._serialized_start=292
  _globals['_ISOCHRONE']._serialized_end=373
  _globals['_WAREHOUSECONTROLLER']._serialized_start=376
  _globals['_WAREHOUSECONTROLLER']._serialized_end=864
# @@protoc_insertion_point(module_scope)
