# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isochrone.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fisochrone.proto\x12\tisochrone\x1a\x1bgoogle/protobuf/empty.proto\",\n\x14IsochroneListRequest\x12\x14\n\x0cwarehouse_id\x18\x01 \x01(\x03\"B\n\x18IsochroneRetrieveRequest\x12\x14\n\x0cwarehouse_id\x18\x01 \x01(\x03\x12\x10\n\x08timespan\x18\x02 \x01(\x03\"Q\n\tIsochrone\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x14\n\x0cwarehouse_id\x18\x02 \x01(\x03\x12\x10\n\x08timespan\x18\x03 \x01(\x03\x12\x10\n\x08\x61ll_geom\x18\x04 \x01(\t\"1\n\x07Railway\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0b\n\x03iid\x18\x02 \x01(\x03\x12\r\n\x05point\x18\x04 \x01(\t2\xb5\x02\n\x13IsochroneController\x12\x41\n\x04List\x12\x1f.isochrone.IsochroneListRequest\x1a\x14.isochrone.Isochrone\"\x00\x30\x01\x12G\n\x08Retrieve\x12#.isochrone.IsochroneRetrieveRequest\x1a\x14.isochrone.Isochrone\"\x00\x12\x45\n\x06\x44\x65lete\x12#.isochrone.IsochroneRetrieveRequest\x1a\x14.isochrone.Isochrone\"\x00\x12K\n\x0cListRailways\x12#.isochrone.IsochroneRetrieveRequest\x1a\x12.isochrone.Railway\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'isochrone_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ISOCHRONELISTREQUEST']._serialized_start=59
  _globals['_ISOCHRONELISTREQUEST']._serialized_end=103
  _globals['_ISOCHRONERETRIEVEREQUEST']._serialized_start=105
  _globals['_ISOCHRONERETRIEVEREQUEST']._serialized_end=171
  _globals['_ISOCHRONE']._serialized_start=173
  _globals['_ISOCHRONE']._serialized_end=254
  _globals['_RAILWAY']._serialized_start=256
  _globals['_RAILWAY']._serialized_end=305
  _globals['_ISOCHRONECONTROLLER']._serialized_start=308
  _globals['_ISOCHRONECONTROLLER']._serialized_end=617
# @@protoc_insertion_point(module_scope)
