# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import railway_pb2 as railway__pb2


class RailwayControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/railway.RailwayController/List',
                request_serializer=railway__pb2.RailwayListRequest.SerializeToString,
                response_deserializer=railway__pb2.Railway.FromString,
                )
        self.ListNeighborhood = channel.unary_stream(
                '/railway.RailwayController/ListNeighborhood',
                request_serializer=railway__pb2.NeighborhoodListRequest.SerializeToString,
                response_deserializer=railway__pb2.Neighborhood.FromString,
                )
        self.ListNeighborhoodOp = channel.unary_stream(
                '/railway.RailwayController/ListNeighborhoodOp',
                request_serializer=railway__pb2.NeighborhoodOpListRequest.SerializeToString,
                response_deserializer=railway__pb2.NeighborhoodOp.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/railway.RailwayController/Retrieve',
                request_serializer=railway__pb2.RailwayRetrieveRequest.SerializeToString,
                response_deserializer=railway__pb2.Railway.FromString,
                )
        self.RetrieveNeighborhood = channel.unary_unary(
                '/railway.RailwayController/RetrieveNeighborhood',
                request_serializer=railway__pb2.NeighborhoodRetrieveRequest.SerializeToString,
                response_deserializer=railway__pb2.Neighborhood.FromString,
                )
        self.RetrieveNeighborhoodOp = channel.unary_unary(
                '/railway.RailwayController/RetrieveNeighborhoodOp',
                request_serializer=railway__pb2.NeighborhoodOpRetrieveRequest.SerializeToString,
                response_deserializer=railway__pb2.NeighborhoodOp.FromString,
                )
        self.Delete = channel.unary_unary(
                '/railway.RailwayController/Delete',
                request_serializer=railway__pb2.RailwayRetrieveRequest.SerializeToString,
                response_deserializer=railway__pb2.Railway.FromString,
                )
        self.DeleteNeighborhood = channel.unary_unary(
                '/railway.RailwayController/DeleteNeighborhood',
                request_serializer=railway__pb2.NeighborhoodOpRetrieveRequest.SerializeToString,
                response_deserializer=railway__pb2.Railway.FromString,
                )
        self.Create = channel.unary_unary(
                '/railway.RailwayController/Create',
                request_serializer=railway__pb2.Railway.SerializeToString,
                response_deserializer=railway__pb2.Railway.FromString,
                )
        self.CreateNeigborhood = channel.unary_unary(
                '/railway.RailwayController/CreateNeigborhood',
                request_serializer=railway__pb2.Neighborhood.SerializeToString,
                response_deserializer=railway__pb2.Neighborhood.FromString,
                )
        self.OptimizeNeighborhood = channel.unary_unary(
                '/railway.RailwayController/OptimizeNeighborhood',
                request_serializer=railway__pb2.OptimizeRequest.SerializeToString,
                response_deserializer=railway__pb2.Optimized.FromString,
                )


class RailwayControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNeighborhood(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNeighborhoodOp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveNeighborhood(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveNeighborhoodOp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNeighborhood(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNeigborhood(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OptimizeNeighborhood(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RailwayControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=railway__pb2.RailwayListRequest.FromString,
                    response_serializer=railway__pb2.Railway.SerializeToString,
            ),
            'ListNeighborhood': grpc.unary_stream_rpc_method_handler(
                    servicer.ListNeighborhood,
                    request_deserializer=railway__pb2.NeighborhoodListRequest.FromString,
                    response_serializer=railway__pb2.Neighborhood.SerializeToString,
            ),
            'ListNeighborhoodOp': grpc.unary_stream_rpc_method_handler(
                    servicer.ListNeighborhoodOp,
                    request_deserializer=railway__pb2.NeighborhoodOpListRequest.FromString,
                    response_serializer=railway__pb2.NeighborhoodOp.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=railway__pb2.RailwayRetrieveRequest.FromString,
                    response_serializer=railway__pb2.Railway.SerializeToString,
            ),
            'RetrieveNeighborhood': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveNeighborhood,
                    request_deserializer=railway__pb2.NeighborhoodRetrieveRequest.FromString,
                    response_serializer=railway__pb2.Neighborhood.SerializeToString,
            ),
            'RetrieveNeighborhoodOp': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveNeighborhoodOp,
                    request_deserializer=railway__pb2.NeighborhoodOpRetrieveRequest.FromString,
                    response_serializer=railway__pb2.NeighborhoodOp.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=railway__pb2.RailwayRetrieveRequest.FromString,
                    response_serializer=railway__pb2.Railway.SerializeToString,
            ),
            'DeleteNeighborhood': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNeighborhood,
                    request_deserializer=railway__pb2.NeighborhoodOpRetrieveRequest.FromString,
                    response_serializer=railway__pb2.Railway.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=railway__pb2.Railway.FromString,
                    response_serializer=railway__pb2.Railway.SerializeToString,
            ),
            'CreateNeigborhood': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNeigborhood,
                    request_deserializer=railway__pb2.Neighborhood.FromString,
                    response_serializer=railway__pb2.Neighborhood.SerializeToString,
            ),
            'OptimizeNeighborhood': grpc.unary_unary_rpc_method_handler(
                    servicer.OptimizeNeighborhood,
                    request_deserializer=railway__pb2.OptimizeRequest.FromString,
                    response_serializer=railway__pb2.Optimized.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'railway.RailwayController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RailwayController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/railway.RailwayController/List',
            railway__pb2.RailwayListRequest.SerializeToString,
            railway__pb2.Railway.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListNeighborhood(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/railway.RailwayController/ListNeighborhood',
            railway__pb2.NeighborhoodListRequest.SerializeToString,
            railway__pb2.Neighborhood.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListNeighborhoodOp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/railway.RailwayController/ListNeighborhoodOp',
            railway__pb2.NeighborhoodOpListRequest.SerializeToString,
            railway__pb2.NeighborhoodOp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/railway.RailwayController/Retrieve',
            railway__pb2.RailwayRetrieveRequest.SerializeToString,
            railway__pb2.Railway.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveNeighborhood(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/railway.RailwayController/RetrieveNeighborhood',
            railway__pb2.NeighborhoodRetrieveRequest.SerializeToString,
            railway__pb2.Neighborhood.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveNeighborhoodOp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/railway.RailwayController/RetrieveNeighborhoodOp',
            railway__pb2.NeighborhoodOpRetrieveRequest.SerializeToString,
            railway__pb2.NeighborhoodOp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/railway.RailwayController/Delete',
            railway__pb2.RailwayRetrieveRequest.SerializeToString,
            railway__pb2.Railway.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteNeighborhood(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/railway.RailwayController/DeleteNeighborhood',
            railway__pb2.NeighborhoodOpRetrieveRequest.SerializeToString,
            railway__pb2.Railway.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/railway.RailwayController/Create',
            railway__pb2.Railway.SerializeToString,
            railway__pb2.Railway.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateNeigborhood(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/railway.RailwayController/CreateNeigborhood',
            railway__pb2.Neighborhood.SerializeToString,
            railway__pb2.Neighborhood.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OptimizeNeighborhood(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/railway.RailwayController/OptimizeNeighborhood',
            railway__pb2.OptimizeRequest.SerializeToString,
            railway__pb2.Optimized.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
